version: "3.1"
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:${DB_PORT}
    networks:
      - mariadb-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mariadb-compose-network

networks:
  mariadb-compose-network:
    driver: bridge
